# This is a workflow to clean sandbox environment

name: sandboxCleanup

# Workflow will trigger on schedule
on:
  pull_request:
  schedule:
    - cron: "0 2-4 * * 1-5"
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  dry-run:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} != "master" && ${{ github.event_name }} == "workflow_dispatch"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: a195073b-b973-4117-a04e-278e0bc31f39 # Sandbox Cleanup
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Running Script in Dry-Run mode
        id: script
        run: ./pipeline-scripts/cleardown.sh --dry-run 

  delete-resources:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} == "master" && ${{ github.event_name }} != "workflow_dispatch"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: a195073b-b973-4117-a04e-278e0bc31f39 # Sandbox Cleanup
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Running Script
        id: script
        run: ./pipeline-scripts/cleardown.sh --delete_resources ${{ secrets.REGISTRYSLACKWEBHOOK }} ${{ secrets.REGISTRYSLACKWEBHOOK }}
  warn:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} == "master" && ${{ github.event_name }} != "workflow_dispatch"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: a195073b-b973-4117-a04e-278e0bc31f39 # Sandbox Cleanup
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Running Script
        id: script
        run: ./pipeline-scripts/cleardown.sh --warn ${{ secrets.REGISTRYSLACKWEBHOOK }} ${{ secrets.REGISTRYSLACKWEBHOOK }}