# This is a workflow to clean sandbox environment

name: sandboxCleanup

# Workflow will trigger on schedule
on:
  schedule:
    - cron: "0 2-4 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Starting
        run: echo Staring cleanup Script..
      - name: Running Script in Dry-Run mode
        run: ./cleardown.sh
      - name: Complete
        run: echo Script Execution Completed !!
